# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       xf86-video-fbturbo

# >> macros
# << macros

Summary:    Xorg omap video driver
Version:    0.2.0
Release:    1
Group:      System/X11
License:    MIT
URL:        https://github.com/hglm/xf86-video-fbturbo
Source0:    %{name}-%{version}.tar.bz2
Source1:    99-mali-devices.rules
Source100:  xf86-video-fbturbo.yaml
BuildRequires:  pkgconfig(xorg-macros)
BuildRequires:  pkgconfig(xorg-server)
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(fontsproto)
BuildRequires:  pkgconfig(xf86driproto)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(udev)
BuildRequires:  sunxi-mali-devel

%description
Xorg DDX driver for the devices based on Allwinner A10/A13 SoC.


%package example-xorg-conf
Summary:    Example fbturbo Xorg config
Group:      System/X11
Requires:   %{name} = %{version}-%{release}

%description example-xorg-conf
Xorg config example for fbturbo



%prep
%setup -q -n %{name}-%{version}/xf86-video-fbturbo

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mkdir -p %{buildroot}/%{_sysconfdir}/X11/xorg.conf.d/
mkdir -p %{buildroot}/%{_sysconfdir}/udev/rules.d/
install -m 644 xorg.conf %{buildroot}/%{_sysconfdir}/X11/xorg.conf.d/99-mali400.conf
install -m 644 %{SOURCE1} %{buildroot}/%{_sysconfdir}/udev/rules.d/99-mali-devices.rules
# << install post


%files
%defattr(-,root,root,-)
%{_libdir}/xorg/modules/drivers/fbturbo_drv.so
%{_datadir}/man/man4/fbturbo.4.gz
%{_sysconfdir}/udev/rules.d/99-mali-devices.rules
# >> files
# << files

%files example-xorg-conf
%defattr(-,root,root,-)
%{_sysconfdir}/X11/xorg.conf.d/99-mali400.conf
# >> files example-xorg-conf
# << files example-xorg-conf
